### ISSUE TITLE
Test vcf file

### ISSUE THREAD

**Issue by alig99** [bahlolab/cavalier#1]
Hi, are you able to supply a test annovar_vcf file? I'm getting this error in R
> vars <- load_annovar_vcf(ANNOVAR_vcf, sampleID)
Meta line 0 read in.
All meta lines processed.
Character matrix gt created.
Character matrix gt rows: 144
Character matrix gt cols: 8
skip: 0
nrows: 144
row_num: 0

 *** caught segfault ***
address 0x8, cause 'memory not mapped'
And I'm assuming it's because my vcf file is incorrect, thanks

**Comment by mfbennett** [comment]
I have added an example of the script that I use to annotate VCF files using vcfanno and ANNOVAR, which produces annotated VCF file containing all the fields that the load_annovar_vcf function expects to find. I hope this will help illustrate the problem. If not, feel free to email me an example of the VCF file and I would be happy to see where I need to modify this function to make it work in a more general manner.

**Comment by alig99** [comment]
Thanks for the example script to annotate VCF files so that load_annovar_vcf function can run.

I then run R & the commands from the cavalier_example.R script.  I get as far as getting qualvars.  But when I run candvars & then list candvars it says NULL. I did have plenty of variants in qualvars, but then they all get filtered out.  All my values in the MAF ESP6500 & MAF 1000G columns are zero.  Is it something to do with this? Whereas there are values in MAF ExAC & MAF gnomAD exome & genome columns.

Plus what does the R,A stand for in Proband depth as the first value is either 0 or 1 ?

It would be really useful to have some documentation on how to use Cavalier.  I know it's fairly new software, but we are really excited to try to use it as it's capabilities will be very helpful to our work.

**Comment by mfbennett** [comment]
Edited above comment to remove email signature, etc, and replied via email to answer questions and attempt to fix issues.

Thanks also for great suggestion about wiki.
