### ISSUE TITLE
candvars = NULL

### ISSUE THREAD

**Issue by alig99** [bahlolab/cavalier#2]
Hi Mark,
When I run R & the commands from the cavalier_example.R script I only get as far as getting qualvars.  
But when I run candvars & then list candvars it says NULL. 
I did have plenty of variants in qualvars, but then they all get filtered out.  
All my values in the MAF ESP6500 & MAF 1000G columns are zero.  
Whereas there are values in MAF ExAC & MAF gnomAD exome & genome columns.
We managed to get Cavalier to run to the end by commenting out part of this line in filter_variants.R
MAF_filter <- MAF_ExAC_filter & MAF_gnomAD_filter #& MAF_ESP6500_filter & MAF_1000G_filter

But when I opened a new window & ran the same script on the same vcf in a new R session it reverted back to candvars NULL even though the change above was still saved!

Also, is there a limit on what size vcf file the program can accept & how many individuals it can manage within a vcf file?

Please can you help, we're really keen to use this great program thanks, ali

**Comment by mfbennett** [comment]
Closing issue as corresponding via email to fix issues.
